name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: false
        type: string

jobs:
  release:
    name: Publish package
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: seaofvoices/release-luau-package-action@v1
        with:
          release-tag: ${{ inputs.version }}
          package-manager: yarn
          artifacts: >-
            [
              {"name":"luaubox.luau","path":"dist/luaubox.luau","content-type":"text/plain"}
            ]
